### PR TITLE
Lance develop

### PR DESCRIPTION
**Pull request by lhannest**

### CODE REVIEW

**Comment by cmungall** [comment]
looks like it configures it to run on 0.0.0.0

**Comment by lhannest** [comment]
Should it be otherwise? By default Flask runs at http://127.0.0.1:5000/.

**Comment by kltm** [comment]
0.0.0.0 is accept from all; as it is in a container, that is up to the hosting network settings and unlikely to be a security issue. That it is on :5000 shoud be mentioned so that people doing the setup can map as they see fit for development and deployment.

**Comment by lhannest** [comment]
Okay, thanks @kltm

**Comment by RichardBruskiewich** [comment]
We're running it as a Docker container with port remapping so not a problem

**Pull request merged**
